// Generated by CoffeeScript 1.3.3
(function() {

  window.Globals = (function() {
    var mapXSpace, parallelData, sessionIntSpace, sessionXSpace, sessionYSpace, whiteSpace, xSchedule, xSpace, ySchedule, ySpace;

    function Globals() {}



    Globals.colors = {
      bordeaux: {
        color: "#98343c",
        rooms: ["bordeaux", "342a", "343", "361", "362/363"]
      },
      havane: {
        color: "#d3783c",
        rooms: ["havane", "351", "352ab"]
      },
      bleu: {
        color: "#1b5576",
        rooms: ["blue", "241", "242ab", "242a", "242b", "243"]
      },
      green: {
        color: "#265e30",
        rooms: ["251", "252a", "252b", "253"]
      },
      interact: {
        color: "#61447a",
        rooms: []
      },
      chi: {
        color: "#2a276d",
        rooms: []
      },
      grand: {
        color: "#f1d32e",
        rooms: ["grand"]
      }
    };

    Globals.clcScreen = navigator.appVersion.indexOf("Linux") !== -1

    Globals.vennEvent = null;

    Globals.threshold = 12; //Threshold for the venn diagram

    Globals.textThreshold = 20;  // Text threshold

    Globals.height = $(window).height();

    Globals.width = Globals.clcScreen ? $(window).width() : $(window).width();

    xSchedule = 730;

    ySchedule = 200;

    Globals.humanReadableMode = {"sessions": "Session", "map": "Room", "comm": "Communities"}

    xSpace = 280;

    ySpace = 220;

    parallelData = void 0;

    mapXSpace = 670;

    sessionIntSpace = Globals.clcScreen ? 52 : 55;

    sessionXSpace = 390;

    sessionYSpace = Globals.clcScreen ? 115 : 163; //225

    whiteSpace = 20;

    Globals.topMargin = 100;
    Globals.leftMargin = 100;

    Globals.fociFree = [
      {
        x: Globals.width / 2,
        y: Globals.height / 2
      }
    ];

    Globals.fociSchedule = [
      {
        x: xSchedule,
        y: ySchedule
      }, {
        x: xSchedule + xSpace,
        y: ySchedule
      }, {
        x: xSchedule + xSpace * 2,
        y: ySchedule
      }, {
        x: xSchedule + xSpace * 3,
        y: ySchedule
      }, {
        x: xSchedule,
        y: ySchedule + ySpace
      }, {
        x: xSchedule + xSpace,
        y: ySchedule + ySpace
      }, {
        x: xSchedule + xSpace * 2,
        y: ySchedule + ySpace
      }, {
        x: xSchedule + xSpace * 3,
        y: ySchedule + ySpace
      }, {
        x: xSchedule,
        y: ySchedule + ySpace * 2
      }, {
        x: xSchedule + xSpace,
        y: ySchedule + ySpace * 2
      }, {
        x: xSchedule + xSpace * 2,
        y: ySchedule + ySpace * 2
      }, {
        x: xSchedule + xSpace * 3,
        y: ySchedule + ySpace * 2
      }, {
        x: xSchedule,
        y: ySchedule + ySpace * 3
      }, {
        x: xSchedule + xSpace,
        y: ySchedule + ySpace * 3
      }, {
        x: xSchedule + xSpace * 2,
        y: ySchedule + ySpace * 3
      }, {
        x: xSchedule + xSpace * 3,
        y: ySchedule + ySpace * 3
      }, {
        x: xSchedule + xSpace * 4,
        y: ySchedule + ySpace * 2
      }
    ];

    Globals.fociMap = {
      "352ab":    {x: mapXSpace + 243,  y: 47},
      "351":      {x: mapXSpace + 77,  y: 88},
      "havane":   {x: mapXSpace + 3,  y: 199},
      "362/363":  {x: mapXSpace + 470, y: 102},
      "361":      {x: mapXSpace + 438, y: 160},
      "343":      {x: mapXSpace + 386, y: 198},
      "342a":     {x: mapXSpace + 305, y: 250},
      "bordeaux": {x: mapXSpace + 167, y: 280},
      "253":      {x: mapXSpace + 306, y: 409},
      "252b":     {x: mapXSpace + 212, y: 420},
      "252a":     {x: mapXSpace + 121, y: 442},
      "251":      {x: mapXSpace + 32,  y: 467},
      "blue":     {x: mapXSpace + 448, y: 430},
      "243":      {x: mapXSpace + 463, y: 492},
      "242b":     {x: mapXSpace + 425, y: 540},
      "242ab":    {x: mapXSpace + 376, y: 540},
      "242a":     {x: mapXSpace + 370, y: 582},
      "241":      {x: mapXSpace + 308, y: 618},
      "grand":    {x: mapXSpace + 48,  y: 852},
      undefined:  {x: 2 * mapXSpace + 1000,  y: 600}
    };

  Globals.fociSession = {
      "monday 9:00 blue":     {x: sessionXSpace + sessionIntSpace * 0,  y: sessionYSpace + sessionIntSpace * 0},
      "monday 11:00 blue":    {x: sessionXSpace + sessionIntSpace * 0,  y: sessionYSpace + sessionIntSpace * 1},
      "monday 14:00 blue":    {x: sessionXSpace + sessionIntSpace * 0,  y: sessionYSpace + sessionIntSpace * 2},
      "monday 16:00 blue":    {x: sessionXSpace + sessionIntSpace * 0,  y: sessionYSpace + sessionIntSpace * 3},
      "tuesday 9:00 blue":    {x: sessionXSpace + sessionIntSpace * 0,  y: whiteSpace + sessionYSpace + sessionIntSpace * 4},
      "tuesday 11:00 blue":   {x: sessionXSpace + sessionIntSpace * 0,  y: whiteSpace + sessionYSpace + sessionIntSpace * 5},
      "tuesday 14:00 blue":   {x: sessionXSpace + sessionIntSpace * 0,  y: whiteSpace + sessionYSpace + sessionIntSpace * 6},
      "tuesday 16:00 blue":   {x: sessionXSpace + sessionIntSpace * 0,  y: whiteSpace + sessionYSpace + sessionIntSpace * 7},
      "wednesday 9:00 blue":  {x: sessionXSpace + sessionIntSpace * 0,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 8},
      "wednesday 11:00 blue": {x: sessionXSpace + sessionIntSpace * 0,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 9},
      "wednesday 14:00 blue": {x: sessionXSpace + sessionIntSpace * 0,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 10},
      "wednesday 16:00 blue": {x: sessionXSpace + sessionIntSpace * 0,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 11},
      "thursday 9:00 blue":   {x: sessionXSpace + sessionIntSpace * 0,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 12},
      "thursday 11:00 blue":  {x: sessionXSpace + sessionIntSpace * 0,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 13},
      "thursday 14:00 blue":  {x: sessionXSpace + sessionIntSpace * 0,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 14},
      "thursday 16:00 blue":  {x: sessionXSpace + sessionIntSpace * 0,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 15},
      //241
      "monday 9:00 241":     {x: 45 + sessionXSpace + sessionIntSpace * 1,  y: sessionYSpace + sessionIntSpace * 0},
      "monday 11:00 241":    {x: 45 + sessionXSpace + sessionIntSpace * 1,  y: sessionYSpace + sessionIntSpace * 1},
      "monday 14:00 241":    {x: 45 + sessionXSpace + sessionIntSpace * 1,  y: sessionYSpace + sessionIntSpace * 2},
      "monday 16:00 241":    {x: 45 + sessionXSpace + sessionIntSpace * 1,  y: sessionYSpace + sessionIntSpace * 3},
      "tuesday 9:00 241":    {x: 45 + sessionXSpace + sessionIntSpace * 1,  y: whiteSpace + sessionYSpace + sessionIntSpace * 4},
      "tuesday 11:00 241":   {x: 45 + sessionXSpace + sessionIntSpace * 1,  y: whiteSpace + sessionYSpace + sessionIntSpace * 5},
      "tuesday 14:00 241":   {x: 45 + sessionXSpace + sessionIntSpace * 1,  y: whiteSpace + sessionYSpace + sessionIntSpace * 6},
      "tuesday 16:00 241":   {x: 45 + sessionXSpace + sessionIntSpace * 1,  y: whiteSpace + sessionYSpace + sessionIntSpace * 7},
      "wednesday 9:00 241":  {x: 45 + sessionXSpace + sessionIntSpace * 1,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 8},
      "wednesday 11:00 241": {x: 45 + sessionXSpace + sessionIntSpace * 1,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 9},
      "wednesday 14:00 241": {x: 45 + sessionXSpace + sessionIntSpace * 1,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 10},
      "wednesday 16:00 241": {x: 45 + sessionXSpace + sessionIntSpace * 1,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 11},
      "thursday 9:00 241":   {x: 45 + sessionXSpace + sessionIntSpace * 1,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 12},
      "thursday 11:00 241":  {x: 45 + sessionXSpace + sessionIntSpace * 1,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 13},
      "thursday 14:00 241":  {x: 45 + sessionXSpace + sessionIntSpace * 1,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 14},
      "thursday 16:00 241":  {x: 45 + sessionXSpace + sessionIntSpace * 1,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 15},
      //242ab
      "monday 9:00 242ab":      {x: 120 + sessionXSpace + sessionIntSpace * 2,  y: sessionYSpace + sessionIntSpace * 0},
      "monday 11:00 242ab":     {x: 120 + sessionXSpace + sessionIntSpace * 2,  y: sessionYSpace + sessionIntSpace * 1},
      "monday 14:00 242ab":     {x: 120 + sessionXSpace + sessionIntSpace * 2,  y: sessionYSpace + sessionIntSpace * 2},
      "monday 16:00 242ab":     {x: 120 + sessionXSpace + sessionIntSpace * 2,  y: sessionYSpace + sessionIntSpace * 3},
      "tuesday 9:00 242ab":     {x: 120 + sessionXSpace + sessionIntSpace * 2,  y: whiteSpace + sessionYSpace + sessionIntSpace * 4},
      "tuesday 11:00 242ab":    {x: 120 + sessionXSpace + sessionIntSpace * 2,  y: whiteSpace + sessionYSpace + sessionIntSpace * 5},
      "tuesday 14:00 242ab":    {x: 120 + sessionXSpace + sessionIntSpace * 2,  y: whiteSpace + sessionYSpace + sessionIntSpace * 6},
      "tuesday 16:00 242ab":    {x: 120 + sessionXSpace + sessionIntSpace * 2,  y: whiteSpace + sessionYSpace + sessionIntSpace * 7},
      "wednesday 9:00 242ab":   {x: 120 + sessionXSpace + sessionIntSpace * 2,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 8},
      "wednesday 11:00 242ab":  {x: 120 + sessionXSpace + sessionIntSpace * 2,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 9},
      "wednesday 14:00 242ab":  {x: 120 + sessionXSpace + sessionIntSpace * 2,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 10},
      "wednesday 16:00 242ab":  {x: 120 + sessionXSpace + sessionIntSpace * 2,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 11},
      "thursday 9:00 242b":     {x: 120 + sessionXSpace + sessionIntSpace * 2.50,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 12},
      "thursday 11:00 242b":    {x: 120 + sessionXSpace + sessionIntSpace * 2.50,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 13},
      "thursday 14:00 242b":    {x: 120 + sessionXSpace + sessionIntSpace * 2.50,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 14},
      "thursday 16:00 242b":    {x: 120 + sessionXSpace + sessionIntSpace * 2.50,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 15},
      "thursday 9:00 242a":     {x: 120 + sessionXSpace + sessionIntSpace * 1.50,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 12},
      "thursday 11:00 242a":    {x: 120 + sessionXSpace + sessionIntSpace * 1.50,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 13},
      "thursday 14:00 242a":    {x: 120 + sessionXSpace + sessionIntSpace * 1.50,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 14},
      "thursday 16:00 242a":    {x: 120 + sessionXSpace + sessionIntSpace * 1.50,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 15},
      //243
      "monday 9:00 243":     {x: 180 + sessionXSpace + sessionIntSpace * 3,  y: sessionYSpace + sessionIntSpace * 0},
      "monday 11:00 243":    {x: 180 + sessionXSpace + sessionIntSpace * 3,  y: sessionYSpace + sessionIntSpace * 1},
      "monday 14:00 243":    {x: 180 + sessionXSpace + sessionIntSpace * 3,  y: sessionYSpace + sessionIntSpace * 2},
      "monday 16:00 243":    {x: 180 + sessionXSpace + sessionIntSpace * 3,  y: sessionYSpace + sessionIntSpace * 3},
      "tuesday 9:00 243":    {x: 180 + sessionXSpace + sessionIntSpace * 3,  y: whiteSpace + sessionYSpace + sessionIntSpace * 4},
      "tuesday 11:00 243":   {x: 180 + sessionXSpace + sessionIntSpace * 3,  y: whiteSpace + sessionYSpace + sessionIntSpace * 5},
      "tuesday 14:00 243":   {x: 180 + sessionXSpace + sessionIntSpace * 3,  y: whiteSpace + sessionYSpace + sessionIntSpace * 6},
      "tuesday 16:00 243":   {x: 180 + sessionXSpace + sessionIntSpace * 3,  y: whiteSpace + sessionYSpace + sessionIntSpace * 7},
      "wednesday 9:00 243":  {x: 180 + sessionXSpace + sessionIntSpace * 3,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 8},
      "wednesday 11:00 243": {x: 180 + sessionXSpace + sessionIntSpace * 3,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 9},
      "wednesday 14:00 243": {x: 180 + sessionXSpace + sessionIntSpace * 3,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 10},
      "wednesday 16:00 243": {x: 180 + sessionXSpace + sessionIntSpace * 3,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 11},
      "thursday 9:00 243":   {x: 180 + sessionXSpace + sessionIntSpace * 3,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 12},
      "thursday 11:00 243":  {x: 180 + sessionXSpace + sessionIntSpace * 3,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 13},
      "thursday 14:00 243":  {x: 180 + sessionXSpace + sessionIntSpace * 3,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 14},
      "thursday 16:00 243":  {x: 180 + sessionXSpace + sessionIntSpace * 3,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 15},
     

      //251
      "monday 9:00 251":     {x: 220 + sessionXSpace + sessionIntSpace * 4,  y: sessionYSpace + sessionIntSpace * 0},
      "monday 11:00 251":    {x: 220 + sessionXSpace + sessionIntSpace * 4,  y: sessionYSpace + sessionIntSpace * 1},
      "monday 14:00 251":    {x: 220 + sessionXSpace + sessionIntSpace * 4,  y: sessionYSpace + sessionIntSpace * 2},
      "monday 16:00 251":    {x: 220 + sessionXSpace + sessionIntSpace * 4,  y: sessionYSpace + sessionIntSpace * 3},
      "tuesday 9:00 251":    {x: 220 + sessionXSpace + sessionIntSpace * 4,  y: whiteSpace + sessionYSpace + sessionIntSpace * 4},
      "tuesday 11:00 251":   {x: 220 + sessionXSpace + sessionIntSpace * 4,  y: whiteSpace + sessionYSpace + sessionIntSpace * 5},
      "tuesday 14:00 251":   {x: 220 + sessionXSpace + sessionIntSpace * 4,  y: whiteSpace + sessionYSpace + sessionIntSpace * 6},
      "tuesday 16:00 251":   {x: 220 + sessionXSpace + sessionIntSpace * 4,  y: whiteSpace + sessionYSpace + sessionIntSpace * 7},
      "wednesday 9:00 251":  {x: 220 + sessionXSpace + sessionIntSpace * 4,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 8},
      "wednesday 11:00 251": {x: 220 + sessionXSpace + sessionIntSpace * 4,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 9},
      "wednesday 14:00 251": {x: 220 + sessionXSpace + sessionIntSpace * 4,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 10},
      "wednesday 16:00 251": {x: 220 + sessionXSpace + sessionIntSpace * 4,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 11},
      "thursday 9:00 251":   {x: 220 + sessionXSpace + sessionIntSpace * 4,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 12},
      "thursday 11:00 251":  {x: 220 + sessionXSpace + sessionIntSpace * 4,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 13},
      "thursday 14:00 251":  {x: 220 + sessionXSpace + sessionIntSpace * 4,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 14},
      "thursday 16:00 251":  {x: 220 + sessionXSpace + sessionIntSpace * 4,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 15},

      //252a
      "monday 9:00 252a":     {x: 255 + sessionXSpace + sessionIntSpace * 5,  y: sessionYSpace + sessionIntSpace * 0},
      "monday 11:00 252a":    {x: 255 + sessionXSpace + sessionIntSpace * 5,  y: sessionYSpace + sessionIntSpace * 1},
      "monday 14:00 252a":    {x: 255 + sessionXSpace + sessionIntSpace * 5,  y: sessionYSpace + sessionIntSpace * 2},
      "monday 16:00 252a":    {x: 255 + sessionXSpace + sessionIntSpace * 5,  y: sessionYSpace + sessionIntSpace * 3},
      "tuesday 9:00 252a":    {x: 255 + sessionXSpace + sessionIntSpace * 5,  y: whiteSpace + sessionYSpace + sessionIntSpace * 4},
      "tuesday 11:00 252a":   {x: 255 + sessionXSpace + sessionIntSpace * 5,  y: whiteSpace + sessionYSpace + sessionIntSpace * 5},
      "tuesday 14:00 252a":   {x: 255 + sessionXSpace + sessionIntSpace * 5,  y: whiteSpace + sessionYSpace + sessionIntSpace * 6},
      "tuesday 16:00 252a":   {x: 255 + sessionXSpace + sessionIntSpace * 5,  y: whiteSpace + sessionYSpace + sessionIntSpace * 7},
      "wednesday 9:00 252a":  {x: 255 + sessionXSpace + sessionIntSpace * 5,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 8},
      "wednesday 11:00 252a": {x: 255 + sessionXSpace + sessionIntSpace * 5,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 9},
      "wednesday 14:00 252a": {x: 255 + sessionXSpace + sessionIntSpace * 5,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 10},
      "wednesday 16:00 252a": {x: 255 + sessionXSpace + sessionIntSpace * 5,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 11},
      "thursday 9:00 252a":   {x: 255 + sessionXSpace + sessionIntSpace * 5,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 12},
      "thursday 11:00 252a":  {x: 255 + sessionXSpace + sessionIntSpace * 5,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 13},
      "thursday 14:00 252a":  {x: 255 + sessionXSpace + sessionIntSpace * 5,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 14},
      "thursday 16:00 252a":  {x: 255 + sessionXSpace + sessionIntSpace * 5,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 15},

      //252b
      "monday 9:00 252b":     {x: 315 + sessionXSpace + sessionIntSpace * 6,  y: sessionYSpace + sessionIntSpace * 0},
      "monday 11:00 252b":    {x: 315 + sessionXSpace + sessionIntSpace * 6,  y: sessionYSpace + sessionIntSpace * 1},
      "monday 14:00 252b":    {x: 315 + sessionXSpace + sessionIntSpace * 6,  y: sessionYSpace + sessionIntSpace * 2},
      "monday 16:00 252b":    {x: 315 + sessionXSpace + sessionIntSpace * 6,  y: sessionYSpace + sessionIntSpace * 3},
      "tuesday 9:00 252b":    {x: 315 + sessionXSpace + sessionIntSpace * 6,  y: whiteSpace + sessionYSpace + sessionIntSpace * 4},
      "tuesday 11:00 252b":   {x: 315 + sessionXSpace + sessionIntSpace * 6,  y: whiteSpace + sessionYSpace + sessionIntSpace * 5},
      "tuesday 14:00 252b":   {x: 315 + sessionXSpace + sessionIntSpace * 6,  y: whiteSpace + sessionYSpace + sessionIntSpace * 6},
      "tuesday 16:00 252b":   {x: 315 + sessionXSpace + sessionIntSpace * 6,  y: whiteSpace + sessionYSpace + sessionIntSpace * 7},
      "wednesday 9:00 252b":  {x: 315 + sessionXSpace + sessionIntSpace * 6,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 8},
      "wednesday 11:00 252b": {x: 315 + sessionXSpace + sessionIntSpace * 6,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 9},
      "wednesday 14:00 252b": {x: 315 + sessionXSpace + sessionIntSpace * 6,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 10},
      "wednesday 16:00 252b": {x: 315 + sessionXSpace + sessionIntSpace * 6,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 11},
      "thursday 9:00 252b":   {x: 315 + sessionXSpace + sessionIntSpace * 6,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 12},
      "thursday 11:00 252b":  {x: 315 + sessionXSpace + sessionIntSpace * 6,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 13},
      "thursday 14:00 252b":  {x: 315 + sessionXSpace + sessionIntSpace * 6,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 14},
      "thursday 16:00 252b":  {x: 315 + sessionXSpace + sessionIntSpace * 6,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 15},
      //253
      "monday 9:00 253":     {x: 345 + sessionXSpace + sessionIntSpace * 7,  y: sessionYSpace + sessionIntSpace * 0},
      "monday 11:00 253":    {x: 345 + sessionXSpace + sessionIntSpace * 7,  y: sessionYSpace + sessionIntSpace * 1},
      "monday 14:00 253":    {x: 345 + sessionXSpace + sessionIntSpace * 7,  y: sessionYSpace + sessionIntSpace * 2},
      "monday 16:00 253":    {x: 345 + sessionXSpace + sessionIntSpace * 7,  y: sessionYSpace + sessionIntSpace * 3},
      "tuesday 9:00 253":    {x: 345 + sessionXSpace + sessionIntSpace * 7,  y: whiteSpace + sessionYSpace + sessionIntSpace * 4},
      "tuesday 11:00 253":   {x: 345 + sessionXSpace + sessionIntSpace * 7,  y: whiteSpace + sessionYSpace + sessionIntSpace * 5},
      "tuesday 14:00 253":   {x: 345 + sessionXSpace + sessionIntSpace * 7,  y: whiteSpace + sessionYSpace + sessionIntSpace * 6},
      "tuesday 16:00 253":   {x: 345 + sessionXSpace + sessionIntSpace * 7,  y: whiteSpace + sessionYSpace + sessionIntSpace * 7},
      "wednesday 9:00 253":  {x: 345 + sessionXSpace + sessionIntSpace * 7,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 8},
      "wednesday 11:00 253": {x: 345 + sessionXSpace + sessionIntSpace * 7,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 9},
      "wednesday 14:00 253": {x: 345 + sessionXSpace + sessionIntSpace * 7,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 10},
      "wednesday 16:00 253": {x: 345 + sessionXSpace + sessionIntSpace * 7,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 11},
      "thursday 9:00 253":   {x: 345 + sessionXSpace + sessionIntSpace * 7,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 12},
      "thursday 11:00 253":  {x: 345 + sessionXSpace + sessionIntSpace * 7,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 13},
      "thursday 14:00 253":  {x: 345 + sessionXSpace + sessionIntSpace * 7,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 14},
      "thursday 16:00 253":  {x: 345 + sessionXSpace + sessionIntSpace * 7,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 15},

      //bordeaux
      "monday 9:00 bordeaux":     {x: 440 + sessionXSpace + sessionIntSpace * 8,  y: sessionYSpace + sessionIntSpace * 0},
      "monday 11:00 bordeaux":    {x: 440 + sessionXSpace + sessionIntSpace * 8,  y: sessionYSpace + sessionIntSpace * 1},
      "monday 14:00 bordeaux":    {x: 440 + sessionXSpace + sessionIntSpace * 8,  y: sessionYSpace + sessionIntSpace * 2},
      "monday 16:00 bordeaux":    {x: 440 + sessionXSpace + sessionIntSpace * 8,  y: sessionYSpace + sessionIntSpace * 3},
      "tuesday 9:00 bordeaux":    {x: 440 + sessionXSpace + sessionIntSpace * 8,  y: whiteSpace + sessionYSpace + sessionIntSpace * 4},
      "tuesday 11:00 bordeaux":   {x: 440 + sessionXSpace + sessionIntSpace * 8,  y: whiteSpace + sessionYSpace + sessionIntSpace * 5},
      "tuesday 14:00 bordeaux":   {x: 440 + sessionXSpace + sessionIntSpace * 8,  y: whiteSpace + sessionYSpace + sessionIntSpace * 6},
      "tuesday 16:00 bordeaux":   {x: 440 + sessionXSpace + sessionIntSpace * 8,  y: whiteSpace + sessionYSpace + sessionIntSpace * 7},
      "wednesday 9:00 bordeaux":  {x: 440 + sessionXSpace + sessionIntSpace * 8,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 8},
      "wednesday 11:00 bordeaux": {x: 440 + sessionXSpace + sessionIntSpace * 8,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 9},
      "wednesday 14:00 bordeaux": {x: 440 + sessionXSpace + sessionIntSpace * 8,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 10},
      "wednesday 16:00 bordeaux": {x: 440 + sessionXSpace + sessionIntSpace * 8,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 11},
      "thursday 9:00 bordeaux":   {x: 440 + sessionXSpace + sessionIntSpace * 8,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 12},
      "thursday 11:00 bordeaux":  {x: 440 + sessionXSpace + sessionIntSpace * 8,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 13},
      "thursday 14:00 bordeaux":  {x: 440 + sessionXSpace + sessionIntSpace * 8,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 14},
      "thursday 16:00 bordeaux":  {x: 440 + sessionXSpace + sessionIntSpace * 8,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 15},
     //342a
      "monday 9:00 342a":     {x: 525 + sessionXSpace + sessionIntSpace * 9,  y: sessionYSpace + sessionIntSpace * 0},
      "monday 11:00 342a":    {x: 525 + sessionXSpace + sessionIntSpace * 9,  y: sessionYSpace + sessionIntSpace * 1},
      "monday 14:00 342a":    {x: 525 + sessionXSpace + sessionIntSpace * 9,  y: sessionYSpace + sessionIntSpace * 2},
      "monday 16:00 342a":    {x: 525 + sessionXSpace + sessionIntSpace * 9,  y: sessionYSpace + sessionIntSpace * 3},
      "tuesday 9:00 342a":    {x: 525 + sessionXSpace + sessionIntSpace * 9,  y: whiteSpace + sessionYSpace + sessionIntSpace * 4},
      "tuesday 11:00 342a":   {x: 525 + sessionXSpace + sessionIntSpace * 9,  y: whiteSpace + sessionYSpace + sessionIntSpace * 5},
      "tuesday 14:00 342a":   {x: 525 + sessionXSpace + sessionIntSpace * 9,  y: whiteSpace + sessionYSpace + sessionIntSpace * 6},
      "tuesday 16:00 342a":   {x: 525 + sessionXSpace + sessionIntSpace * 9,  y: whiteSpace + sessionYSpace + sessionIntSpace * 7},
      "wednesday 9:00 342a":  {x: 525 + sessionXSpace + sessionIntSpace * 9,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 8},
      "wednesday 11:00 342a": {x: 525 + sessionXSpace + sessionIntSpace * 9,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 9},
      "wednesday 14:00 342a": {x: 525 + sessionXSpace + sessionIntSpace * 9,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 10},
      "wednesday 16:00 342a": {x: 525 + sessionXSpace + sessionIntSpace * 9,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 11},
      "thursday 9:00 342a":   {x: 525 + sessionXSpace + sessionIntSpace * 9,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 12},
      "thursday 11:00 342a":  {x: 525 + sessionXSpace + sessionIntSpace * 9,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 13},
      "thursday 14:00 342a":  {x: 525 + sessionXSpace + sessionIntSpace * 9,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 14},
      "thursday 16:00 342a":  {x: 525 + sessionXSpace + sessionIntSpace * 9,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 15},
     //343
      "monday 9:00 343":     {x: 565 + sessionXSpace + sessionIntSpace * 10,  y: sessionYSpace + sessionIntSpace * 0},
      "monday 11:00 343":    {x: 565 + sessionXSpace + sessionIntSpace * 10,  y: sessionYSpace + sessionIntSpace * 1},
      "monday 14:00 343":    {x: 565 + sessionXSpace + sessionIntSpace * 10,  y: sessionYSpace + sessionIntSpace * 2},
      "monday 16:00 343":    {x: 565 + sessionXSpace + sessionIntSpace * 10,  y: sessionYSpace + sessionIntSpace * 3},
      "tuesday 9:00 343":    {x: 565 + sessionXSpace + sessionIntSpace * 10,  y: whiteSpace + sessionYSpace + sessionIntSpace * 4},
      "tuesday 11:00 343":   {x: 565 + sessionXSpace + sessionIntSpace * 10,  y: whiteSpace + sessionYSpace + sessionIntSpace * 5},
      "tuesday 14:00 343":   {x: 565 + sessionXSpace + sessionIntSpace * 10,  y: whiteSpace + sessionYSpace + sessionIntSpace * 6},
      "tuesday 16:00 343":   {x: 565 + sessionXSpace + sessionIntSpace * 10,  y: whiteSpace + sessionYSpace + sessionIntSpace * 7},
      "wednesday 9:00 343":  {x: 565 + sessionXSpace + sessionIntSpace * 10,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 8},
      "wednesday 11:00 343": {x: 565 + sessionXSpace + sessionIntSpace * 10,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 9},
      "wednesday 14:00 343": {x: 565 + sessionXSpace + sessionIntSpace * 10,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 10},
      "wednesday 16:00 343": {x: 565 + sessionXSpace + sessionIntSpace * 10,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 11},
      "thursday 9:00 343":   {x: 565 + sessionXSpace + sessionIntSpace * 10,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 12},
      "thursday 11:00 343":  {x: 565 + sessionXSpace + sessionIntSpace * 10,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 13},
      "thursday 14:00 343":  {x: 565 + sessionXSpace + sessionIntSpace * 10,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 14},
      "thursday 16:00 343":  {x: 565 + sessionXSpace + sessionIntSpace * 10,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 15},
     //361
      "monday 9:00 361":     {x: 585 + sessionXSpace + sessionIntSpace * 11,  y: sessionYSpace + sessionIntSpace * 0},
      "monday 11:00 361":    {x: 585 + sessionXSpace + sessionIntSpace * 11,  y: sessionYSpace + sessionIntSpace * 1},
      "monday 14:00 361":    {x: 585 + sessionXSpace + sessionIntSpace * 11,  y: sessionYSpace + sessionIntSpace * 2},
      "monday 16:00 361":    {x: 585 + sessionXSpace + sessionIntSpace * 11,  y: sessionYSpace + sessionIntSpace * 3},
      "tuesday 9:00 361":    {x: 585 + sessionXSpace + sessionIntSpace * 11,  y: whiteSpace + sessionYSpace + sessionIntSpace * 4},
      "tuesday 11:00 361":   {x: 585 + sessionXSpace + sessionIntSpace * 11,  y: whiteSpace + sessionYSpace + sessionIntSpace * 5},
      "tuesday 14:00 361":   {x: 585 + sessionXSpace + sessionIntSpace * 11,  y: whiteSpace + sessionYSpace + sessionIntSpace * 6},
      "tuesday 16:00 361":   {x: 585 + sessionXSpace + sessionIntSpace * 11,  y: whiteSpace + sessionYSpace + sessionIntSpace * 7},
      "wednesday 9:00 361":  {x: 585 + sessionXSpace + sessionIntSpace * 11,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 8},
      "wednesday 11:00 361": {x: 585 + sessionXSpace + sessionIntSpace * 11,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 9},
      "wednesday 14:00 361": {x: 585 + sessionXSpace + sessionIntSpace * 11,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 10},
      "wednesday 16:00 361": {x: 585 + sessionXSpace + sessionIntSpace * 11,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 11},
      "thursday 9:00 361":   {x: 585 + sessionXSpace + sessionIntSpace * 11,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 12},
      "thursday 11:00 361":  {x: 585 + sessionXSpace + sessionIntSpace * 11,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 13},
      "thursday 14:00 361":  {x: 585 + sessionXSpace + sessionIntSpace * 11,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 14},
      "thursday 16:00 361":  {x: 585 + sessionXSpace + sessionIntSpace * 11,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 15},
     //362/363
      "monday 9:00 362/363":     {x: 610 + sessionXSpace + sessionIntSpace * 12,  y: sessionYSpace + sessionIntSpace * 0},
      "monday 11:00 362/363":    {x: 610 + sessionXSpace + sessionIntSpace * 12,  y: sessionYSpace + sessionIntSpace * 1},
      "monday 14:00 362/363":    {x: 610 + sessionXSpace + sessionIntSpace * 12,  y: sessionYSpace + sessionIntSpace * 2},
      "monday 16:00 362/363":    {x: 610 + sessionXSpace + sessionIntSpace * 12,  y: sessionYSpace + sessionIntSpace * 3},
      "tuesday 9:00 362/363":    {x: 610 + sessionXSpace + sessionIntSpace * 12,  y: whiteSpace + sessionYSpace + sessionIntSpace * 4},
      "tuesday 11:00 362/363":   {x: 610 + sessionXSpace + sessionIntSpace * 12,  y: whiteSpace + sessionYSpace + sessionIntSpace * 5},
      "tuesday 14:00 362/363":   {x: 610 + sessionXSpace + sessionIntSpace * 12,  y: whiteSpace + sessionYSpace + sessionIntSpace * 6},
      "tuesday 16:00 362/363":   {x: 610 + sessionXSpace + sessionIntSpace * 12,  y: whiteSpace + sessionYSpace + sessionIntSpace * 7},
      "wednesday 9:00 362/363":  {x: 610 + sessionXSpace + sessionIntSpace * 12,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 8},
      "wednesday 11:00 362/363": {x: 610 + sessionXSpace + sessionIntSpace * 12,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 9},
      "wednesday 14:00 362/363": {x: 610 + sessionXSpace + sessionIntSpace * 12,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 10},
      "wednesday 16:00 362/363": {x: 610 + sessionXSpace + sessionIntSpace * 12,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 11},
      "thursday 9:00 362/363":   {x: 610 + sessionXSpace + sessionIntSpace * 12,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 12},
      "thursday 11:00 362/363":  {x: 610 + sessionXSpace + sessionIntSpace * 12,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 13},
      "thursday 14:00 362/363":  {x: 610 + sessionXSpace + sessionIntSpace * 12,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 14},
      "thursday 16:00 362/363":  {x: 610 + sessionXSpace + sessionIntSpace * 12,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 15},
     //havane
      "monday 9:00 havane":     {x: 670 + sessionXSpace + sessionIntSpace * 13,  y: sessionYSpace + sessionIntSpace * 0},
      "monday 11:00 havane":    {x: 670 + sessionXSpace + sessionIntSpace * 13,  y: sessionYSpace + sessionIntSpace * 1},
      "monday 14:00 havane":    {x: 670 + sessionXSpace + sessionIntSpace * 13,  y: sessionYSpace + sessionIntSpace * 2},
      "monday 16:00 havane":    {x: 670 + sessionXSpace + sessionIntSpace * 13,  y: sessionYSpace + sessionIntSpace * 3},
      "tuesday 9:00 havane":    {x: 670 + sessionXSpace + sessionIntSpace * 13,  y: whiteSpace + sessionYSpace + sessionIntSpace * 4},
      "tuesday 11:00 havane":   {x: 670 + sessionXSpace + sessionIntSpace * 13,  y: whiteSpace + sessionYSpace + sessionIntSpace * 5},
      "tuesday 14:00 havane":   {x: 670 + sessionXSpace + sessionIntSpace * 13,  y: whiteSpace + sessionYSpace + sessionIntSpace * 6},
      "tuesday 16:00 havane":   {x: 670 + sessionXSpace + sessionIntSpace * 13,  y: whiteSpace + sessionYSpace + sessionIntSpace * 7},
      "wednesday 9:00 havane":  {x: 670 + sessionXSpace + sessionIntSpace * 13,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 8},
      "wednesday 11:00 havane": {x: 670 + sessionXSpace + sessionIntSpace * 13,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 9},
      "wednesday 14:00 havane": {x: 670 + sessionXSpace + sessionIntSpace * 13,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 10},
      "wednesday 16:00 havane": {x: 670 + sessionXSpace + sessionIntSpace * 13,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 11},
      "thursday 9:00 havane":   {x: 670 + sessionXSpace + sessionIntSpace * 13,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 12},
      "thursday 11:00 havane":  {x: 670 + sessionXSpace + sessionIntSpace * 13,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 13},
      "thursday 14:00 havane":  {x: 670 + sessionXSpace + sessionIntSpace * 13,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 14},
      "thursday 16:00 havane":  {x: 670 + sessionXSpace + sessionIntSpace * 13,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 15},
     //351
      "monday 9:00 351":     {x: 725 + sessionXSpace + sessionIntSpace * 14,  y: sessionYSpace + sessionIntSpace * 0},
      "monday 11:00 351":    {x: 725 + sessionXSpace + sessionIntSpace * 14,  y: sessionYSpace + sessionIntSpace * 1},
      "monday 14:00 351":    {x: 725 + sessionXSpace + sessionIntSpace * 14,  y: sessionYSpace + sessionIntSpace * 2},
      "monday 16:00 351":    {x: 725 + sessionXSpace + sessionIntSpace * 14,  y: sessionYSpace + sessionIntSpace * 3},
      "tuesday 9:00 351":    {x: 725 + sessionXSpace + sessionIntSpace * 14,  y: whiteSpace + sessionYSpace + sessionIntSpace * 4},
      "tuesday 11:00 351":   {x: 725 + sessionXSpace + sessionIntSpace * 14,  y: whiteSpace + sessionYSpace + sessionIntSpace * 5},
      "tuesday 14:00 351":   {x: 725 + sessionXSpace + sessionIntSpace * 14,  y: whiteSpace + sessionYSpace + sessionIntSpace * 6},
      "tuesday 16:00 351":   {x: 725 + sessionXSpace + sessionIntSpace * 14,  y: whiteSpace + sessionYSpace + sessionIntSpace * 7},
      "wednesday 9:00 351":  {x: 725 + sessionXSpace + sessionIntSpace * 14,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 8},
      "wednesday 11:00 351": {x: 725 + sessionXSpace + sessionIntSpace * 14,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 9},
      "wednesday 14:00 351": {x: 725 + sessionXSpace + sessionIntSpace * 14,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 10},
      "wednesday 16:00 351": {x: 725 + sessionXSpace + sessionIntSpace * 14,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 11},
      "thursday 9:00 351":   {x: 725 + sessionXSpace + sessionIntSpace * 14,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 12},
      "thursday 11:00 351":  {x: 725 + sessionXSpace + sessionIntSpace * 14,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 13},
      "thursday 14:00 351":  {x: 725 + sessionXSpace + sessionIntSpace * 14,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 14},
      "thursday 16:00 351":  {x: 725 + sessionXSpace + sessionIntSpace * 14,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 15},
     //352ab
      "monday 9:00 352ab":     {x: 760 + sessionXSpace + sessionIntSpace * 15,  y: sessionYSpace + sessionIntSpace * 0},
      "monday 11:00 352ab":    {x: 760 + sessionXSpace + sessionIntSpace * 15,  y: sessionYSpace + sessionIntSpace * 1},
      "monday 14:00 352ab":    {x: 760 + sessionXSpace + sessionIntSpace * 15,  y: sessionYSpace + sessionIntSpace * 2},
      "monday 16:00 352ab":    {x: 760 + sessionXSpace + sessionIntSpace * 15,  y: sessionYSpace + sessionIntSpace * 3},
      "tuesday 9:00 352ab":    {x: 760 + sessionXSpace + sessionIntSpace * 15,  y: whiteSpace + sessionYSpace + sessionIntSpace * 4},
      "tuesday 11:00 352ab":   {x: 760 + sessionXSpace + sessionIntSpace * 15,  y: whiteSpace + sessionYSpace + sessionIntSpace * 5},
      "tuesday 14:00 352ab":   {x: 760 + sessionXSpace + sessionIntSpace * 15,  y: whiteSpace + sessionYSpace + sessionIntSpace * 6},
      "tuesday 16:00 352ab":   {x: 760 + sessionXSpace + sessionIntSpace * 15,  y: whiteSpace + sessionYSpace + sessionIntSpace * 7},
      "wednesday 9:00 352ab":  {x: 760 + sessionXSpace + sessionIntSpace * 15,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 8},
      "wednesday 11:00 352ab": {x: 760 + sessionXSpace + sessionIntSpace * 15,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 9},
      "wednesday 14:00 352ab": {x: 760 + sessionXSpace + sessionIntSpace * 15,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 10},
      "wednesday 16:00 352ab": {x: 760 + sessionXSpace + sessionIntSpace * 15,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 11},
      "thursday 9:00 352ab":   {x: 760 + sessionXSpace + sessionIntSpace * 15,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 12},
      "thursday 11:00 352ab":  {x: 760 + sessionXSpace + sessionIntSpace * 15,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 13},
      "thursday 14:00 352ab":  {x: 760 + sessionXSpace + sessionIntSpace * 15,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 14},
      "thursday 16:00 352ab":  {x: 760 + sessionXSpace + sessionIntSpace * 15,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 15},
     
      //grand
      "monday 9:00 grand":     {x: 815 + sessionXSpace + sessionIntSpace * 16,  y: sessionYSpace + sessionIntSpace * 0},
      "monday 11:00 grand":    {x: 815 + sessionXSpace + sessionIntSpace * 16,  y: sessionYSpace + sessionIntSpace * 1},
      "monday 14:00 grand":    {x: 815 + sessionXSpace + sessionIntSpace * 16,  y: sessionYSpace + sessionIntSpace * 2},
      "monday 16:00 grand":    {x: 815 + sessionXSpace + sessionIntSpace * 16,  y: sessionYSpace + sessionIntSpace * 3},
      "tuesday 9:00 grand":    {x: 815 + sessionXSpace + sessionIntSpace * 16,  y: whiteSpace + sessionYSpace + sessionIntSpace * 4},
      "tuesday 11:00 grand":   {x: 815 + sessionXSpace + sessionIntSpace * 16,  y: whiteSpace + sessionYSpace + sessionIntSpace * 5},
      "tuesday 14:00 grand":   {x: 815 + sessionXSpace + sessionIntSpace * 16,  y: whiteSpace + sessionYSpace + sessionIntSpace * 6},
      "tuesday 16:00 grand":   {x: 815 + sessionXSpace + sessionIntSpace * 16,  y: whiteSpace + sessionYSpace + sessionIntSpace * 7},
      "wednesday 9:00 grand":  {x: 815 + sessionXSpace + sessionIntSpace * 16,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 8},
      "wednesday 11:00 grand": {x: 815 + sessionXSpace + sessionIntSpace * 16,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 9},
      "wednesday 14:00 grand": {x: 815 + sessionXSpace + sessionIntSpace * 16,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 10},
      "wednesday 16:00 grand": {x: 815 + sessionXSpace + sessionIntSpace * 16,  y: whiteSpace * 2 + sessionYSpace + sessionIntSpace * 11},
      "thursday 9:00 grand":   {x: 815 + sessionXSpace + sessionIntSpace * 16,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 12},
      "thursday 11:00 grand":  {x: 815 + sessionXSpace + sessionIntSpace * 16,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 13},
      "thursday 14:00 grand":  {x: 815 + sessionXSpace + sessionIntSpace * 16,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 14},
      "thursday 16:00 grand":  {x: 815 + sessionXSpace + sessionIntSpace * 16,  y: whiteSpace * 3 + sessionYSpace + sessionIntSpace * 15},
     
      undefined: {
        x: sessionXSpace + sessionIntSpace * 16,
        y: sessionYSpace + sessionIntSpace * 0
      }
    };

    return Globals;

  })();

}).call(this);
