// Generated by CoffeeScript 1.3.3
(function() {
  var Hand;

  Hand = (function() {

    function Hand(hand) {
      this.hand = hand;
    }

    Hand.prototype.inBoundaries = function(x, y) {
      return false;
    };

    Hand.prototype.getId = function() {
      return console.log(this.hand);
    };

    return Hand;

  })();

}).call(this);
