// Generated by CoffeeScript 1.3.3
(function() {

  window.Hand = (function() {

    function Hand(hand) {
      this.hand = hand;
    }

    Hand.prototype.inBoundaries = function(x, y) {
      return false;
    };

    Hand.prototype.getId = function() {};

    return Hand;

  })();

}).call(this);
