// Generated by CoffeeScript 1.4.0
(function() {
  var X;

  X = (function() {

    function X() {
      this.update();
    }

    X.prototype.update = function() {};

    X.prototype.fetchData = function() {};

    return X;

  })();

  $(document).ready(function() {
    return new X();
  });

}).call(this);
